db.url=jdbc:oracle:thin:@charlemagne.iutnc.univ-lorraine.fr:1521:infodb
<<<<<<< HEAD
db.user=e52526u
db.password=nilm
=======
db.user=e33433u
db.password=
>>>>>>> 8d5bba242857583500ab496ff191e1d8788d410d
rmi.port=1099
rmi.name=serviceRestaurant