# Connexion au service RMI
rmi.host=localhost
rmi.port=1099
rmi.name=serviceRestaurant

# Port d'écoute du proxy HTTP
http.port=8080

# Proxy IUT pour accéder à Internet depuis les machines de l'IUT
# Laisser vide si non nécessaire (ex: en dehors de l'IUT)
iut.proxy.host=
iut.proxy.port=
