# Connexion au service RMI
rmi.host=localhost
rmi.port=1099
rmi.name=serviceRestaurant

# Port d'écoute du proxy HTTP
http.port=8080

# URL de l'API open data Grand Nancy pour les incidents de circulation
incidents.url=https://carto.g-ny.eu/data/cifs/cifs_waze_v2.json

# Proxy IUT pour accéder à Internet depuis les machines de l'IUT
# Laisser vide si non nécessaire (ex: en dehors de l'IUT)
iut.proxy.host=
iut.proxy.port=
