/* =========================================================
   NETTOYAGE DE LA BASE DE DONNÉES (DROP)
   ========================================================= */
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CONTIENT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE COMMANDE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PLAT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE RESERVATION CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CRENEAU_TABLE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TABLE_RESTAURANT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE RESTAURANT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RESTAURANT';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TABLE_RESTAURANT';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CRENEAU_TABLE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RESERVATION';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PLAT';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COMMANDE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

/* =========================================================
   RESTAURANTS
   ========================================================= */

CREATE TABLE RESTAURANT (
    NUM_RESTAURANT  NUMBER PRIMARY KEY,
    NOM             VARCHAR2(100) NOT NULL,
    ADRESSE         VARCHAR2(255) NOT NULL,
    LATITUDE        NUMBER(9, 6) NOT NULL,
    LONGITUDE       NUMBER(9, 6) NOT NULL,

    CONSTRAINT UQ_RESTAURANT_NOM_ADRESSE
        UNIQUE (NOM, ADRESSE)
);


/* =========================================================
   TABLES PHYSIQUES DES RESTAURANTS
   ========================================================= */

CREATE TABLE TABLE_RESTAURANT (
    NUM_TABLE       NUMBER PRIMARY KEY,
    NUM_RESTAURANT  NUMBER NOT NULL,
    NB_PLACES       NUMBER NOT NULL,

    CONSTRAINT FK_TABLE_RESTAURANT
        FOREIGN KEY (NUM_RESTAURANT)
        REFERENCES RESTAURANT(NUM_RESTAURANT)
);


/* =========================================================
   CRÉNEAUX HORAIRES
   ========================================================= */

CREATE TABLE CRENEAU_TABLE (
    NUM_CRENEAU  NUMBER PRIMARY KEY,
    NUM_TABLE    NUMBER NOT NULL,
    DEBUT        TIMESTAMP NOT NULL,
    FIN          TIMESTAMP NOT NULL,
    STATUT       VARCHAR2(20) DEFAULT 'LIBRE' NOT NULL,

    CONSTRAINT FK_CRENEAU_TABLE
        FOREIGN KEY (NUM_TABLE)
        REFERENCES TABLE_RESTAURANT(NUM_TABLE),

    CONSTRAINT UQ_CRENEAU_TABLE
        UNIQUE (NUM_TABLE, DEBUT, FIN)
);


/* =========================================================
   RÉSERVATIONS
   Une seule réservation peut utiliser un créneau.
   ========================================================= */

CREATE TABLE RESERVATION (
    NUM_RESERVATION  NUMBER PRIMARY KEY,
    NUM_CRENEAU      NUMBER NOT NULL,
    NOM_CLIENT       VARCHAR2(100) NOT NULL,
    PRENOM_CLIENT    VARCHAR2(100) NOT NULL,
    TELEPHONE        VARCHAR2(30) NOT NULL,
    NB_CONVIVES      NUMBER NOT NULL,
    DATE_CREATION    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT FK_RESERVATION_CRENEAU
        FOREIGN KEY (NUM_CRENEAU)
        REFERENCES CRENEAU_TABLE(NUM_CRENEAU),

    CONSTRAINT UQ_RESERVATION_CRENEAU
        UNIQUE (NUM_CRENEAU)
);


/* =========================================================
   PLATS PROPOSÉS PAR LES RESTAURANTS
   ========================================================= */

CREATE TABLE PLAT (
    NUM_PLAT        NUMBER PRIMARY KEY,
    NUM_RESTAURANT  NUMBER NOT NULL,
    LIBELLE         VARCHAR2(100) NOT NULL,
    PRIX_UNITAIRE   NUMBER(10, 2) NOT NULL,
    QTE_STOCKEE     NUMBER NOT NULL,

    CONSTRAINT FK_PLAT_RESTAURANT
        FOREIGN KEY (NUM_RESTAURANT)
        REFERENCES RESTAURANT(NUM_RESTAURANT),

    CONSTRAINT UQ_PLAT_RESTAURANT_LIBELLE
        UNIQUE (NUM_RESTAURANT, LIBELLE)
);


/* =========================================================
   COMMANDES
   Une réservation peut avoir plusieurs commandes.
   ========================================================= */

CREATE TABLE COMMANDE (
    NUM_COMMANDE     NUMBER PRIMARY KEY,
    NUM_RESERVATION  NUMBER NOT NULL,
    DATE_COMMANDE    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    MONTANT          NUMBER(10, 2) DEFAULT 0 NOT NULL,
    STATUT           VARCHAR2(20) DEFAULT 'EN_COURS' NOT NULL,

    CONSTRAINT FK_COMMANDE_RESERVATION
        FOREIGN KEY (NUM_RESERVATION)
        REFERENCES RESERVATION(NUM_RESERVATION)
);


/* =========================================================
   CONTENU DES COMMANDES
   La clé primaire composée empêche d’avoir deux lignes
   séparées pour le même plat dans la même commande.
   ========================================================= */

CREATE TABLE CONTIENT (
    NUM_COMMANDE            NUMBER NOT NULL,
    NUM_PLAT                NUMBER NOT NULL,
    QUANTITE                NUMBER NOT NULL,
    PRIX_UNITAIRE_COMMANDE  NUMBER(10, 2) NOT NULL,

    CONSTRAINT PK_CONTIENT
        PRIMARY KEY (NUM_COMMANDE, NUM_PLAT),

    CONSTRAINT FK_CONTIENT_COMMANDE
        FOREIGN KEY (NUM_COMMANDE)
        REFERENCES COMMANDE(NUM_COMMANDE),

    CONSTRAINT FK_CONTIENT_PLAT
        FOREIGN KEY (NUM_PLAT)
        REFERENCES PLAT(NUM_PLAT)
);


/* =========================================================
   SÉQUENCES ORACLE on fait start with 100 pour ne pas rentrer en conflit avec les valeurs deja existantes
   ========================================================= */

CREATE SEQUENCE SEQ_RESTAURANT
    START WITH 100
    INCREMENT BY 1;

CREATE SEQUENCE SEQ_TABLE_RESTAURANT
    START WITH 100
    INCREMENT BY 1;

CREATE SEQUENCE SEQ_CRENEAU_TABLE
    START WITH 100
    INCREMENT BY 1;

CREATE SEQUENCE SEQ_RESERVATION
    START WITH 100
    INCREMENT BY 1;

CREATE SEQUENCE SEQ_PLAT
    START WITH 100
    INCREMENT BY 1;

CREATE SEQUENCE SEQ_COMMANDE
    START WITH 100
    INCREMENT BY 1;